services:
  hats_api:
    container_name: "hats_api"
    build: .
    ports:
      - "80"
    networks:
      - proxy
    environment:
       VIRTUAL_HOST: hats.snad.space
       DYNDNS_HOST: hats.snad.space
       LETSENCRYPT_HOST: hats.snad.space
       LETSENCRYPT_EMAIL: letsencrypt@snad.space
    restart: always

networks:
  proxy:
    external: true
