[server]
address = "0.0.0.0"
port = 80
show_version = true

[api]
enabled = true
prefix = "/api/v1"

[api.access.s3]
endpoints = []

[api.access.gcs]
endpoints = []

[api.access.azure]
endpoints = []

[api.access.http]
endpoints = ["https://data.lsdb.io"]

[api.access.webdav]
endpoints = []

[data]
filenames = ["*.parq", "*.parquet", "*.pq", "_metadata", "_common_metadata"]

[limits]
max_materialize_bytes = "2GiB"
max_materialize_total_bytes = "8GiB"
max_concurrent_materializations = 4
max_catalog_metadata_bytes = "256MiB"

max_partitions = 16
max_bytes_fetched = "10GiB"
max_rows = 100000

max_concurrent_partitions = 4

max_expression_depth = 10

[[mount]]
path = "/tess/tess_lightcurve"
source = "https://data.lsdb.io/hats/tess/tess_lightcurve"

[[mount]]
path = "/ztf_dr20/zubercal"
source = "https://data.lsdb.io/hats/ztf_dr20/zubercal"

[[mount]]
path = "/macho"
source = "https://data.lsdb.io/hats/macho"
