[server]
address = "0.0.0.0"
port = 80
show_version = true

[api]
enabled = true
prefix = "/api/v1"

[api.access.http]
allow_plain_http = true

[api.access.webdav]
endpoints = ["http://slac.data.lsdb.io:10942/"]

[data]
filenames = ["*.parq", "*.parquet", "*.pq", "_metadata", "_common_metadata"]

[limits]
max_materialize_bytes = "2GiB"
max_materialize_total_bytes = "8GiB"
max_concurrent_materializations = 4
max_catalog_metadata_bytes = "256MiB"

max_partitions = 16
max_bytes_fetched = "10GiB"
max_rows = 100000

max_concurrent_partitions = 4

max_expression_depth = 10
